export const Products = [
    {
        id: 1,
        sku: "SKU125",
        name: "Black Cherry Chunk",
        slug: "black-cherry-chunk",
        image: "/imgs/black-cherry-chunk.webp",
        description: "Cherry ice cream with cherries and chunks of chocolate.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 2,
        sku: "SKU126",
        name: "Caramel Crunch",
        slug: "caramel-crunch",
        image: "/imgs/caramel-crunch.webp",
        description: "Salted caramel ice cream with chocolate covered honeycomb toffee.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 3,
        sku: "SKU127",
        name: "Chocolate Love",
        slug: "chocolate-love",
        image: "/imgs/chocolate-love.webp",
        description: "Dark chocolate ice cream with a chocolate cookie swirl.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 4,
        sku: "SKU128",
        name: "Cookie Dough",
        slug: "cookie-dough",
        image: "/imgs/cookie-dough.webp",
        description: "Brown sugar ice cream with chocolate chips and globs of cookie dough.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 5,
        sku: "SKU129",
        name: "Cookies and Coffee",
        slug: "cookies-and-coffee",
        image: "/imgs/cookies-and-coffee.webp",
        description: "Coffee ice cream with cookie pieces.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 6,
        sku: "SKU130",
        name: "Honey Graham",
        slug: "honey-graham",
        image: "/imgs/honey_graham.webp",
        description: "Graham ice cream with a graham cracker swirl.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 7,
        sku: "SKU131",
        name: "Keep Ya Head Up",
        slug: "keep-ya-head-up",
        image: "/imgs/keep-ya-head-up.webp",
        description:
            "Vanilla ice cream with blackberry sauce and oatmeal crisp - our version of a blackberry crumble with a scoop of vanilla ice crema on top.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 8,
        sku: "SKU132",
        name: "Key Lime Pie",
        slug: "key-lime-pie",
        image: "/imgs/key-lime-pie.webp",
        description: "Key lime ice cream with a graham cracker swirl.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 9,
        sku: "SKU133",
        name: "Matcha Mochi",
        slug: "matcha-mochi",
        image: "/imgs/matcha-mochi.webp",
        description: "Matcha green tea ice cream studded with mini mochi pieces.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 10,
        sku: "SKU134",
        name: "Mintflix and Chillz",
        slug: "mintflix-and-chillz",
        image: "/imgs/mintflix-and-chillz.webp",
        description: "Peppermint ice cream with homemade peppermint patties & a chocolate cookie crumb swirl.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 11,
        sku: "SKU135",
        name: "Non-Dairy Chocolate Love",
        slug: "non-dairy-chocolate-love",
        image: "/imgs/non-dairy-chocolate.webp",
        description: "Dark chocolate ice cream with a chocolate cookie swirl.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 12,
        sku: "SKU136",
        name: "Non-Dairy Roasted Strawberry",
        slug: "non-dairy-roasted-strawberry",
        image: "/imgs/non-dairy-roasted-strawberry.webp",
        description: "Non-dairy strawberry ice cream made with coconut milk.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 13,
        sku: "SKU137",
        name: "Peanut Butter Cup",
        slug: "peanut-butter-cup",
        image: "/imgs/peanut-butter-cup.webp",
        description: "Salted peanut butter ice cream with chunks of crushed peanut butter cups.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 14,
        sku: "SKU138",
        name: "Pistachio",
        slug: "pistachio",
        image: "/imgs/pistachio.webp",
        description: "Pistachio ice cream with a touch of almond flavor.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 15,
        sku: "SKU139",
        name: "Roasted Strawberry",
        slug: "roasted-strawberry",
        image: "/imgs/roasted-strawberry.webp",
        description: "Roasted strawberry are the secret ingredients for this flavor - bold strawberry flavor, creamy, dense texture.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
    {
        id: 16,
        sku: "SKU140",
        name: "Vanilla",
        slug: "vanilla",
        image: "/imgs/vanilla_bean.webp",
        description: "Madagascar vanilla ice cream with specks of vanilla beans.",
        price: 14.0,
        taxable: true,
        isActive: true,
    },
];
